import { buildDiagnosticReportViewModel } from "./buildDiagnosticReportViewModel";
import type { DiagnoseResponse } from "@/lib/types/api";

const baseDiagnosis: DiagnoseResponse = {
  diagnosis_mode: "hybrid",
  areas: [
    {
      area_id: "compensation",
      area_name: "보상",
      score: 55,
      benchmark: 70,
      gap: 15,
      priority: 1,
      difficulty: "medium",
      status_text: "주의",
      issues: [],
      recommendation: "",
      tags: [],
      score_breakdown: [],
    },
    {
      area_id: "evaluation",
      area_name: "평가",
      score: 58,
      benchmark: 70,
      gap: 12,
      priority: 2,
      difficulty: "medium",
      status_text: "주의",
      issues: [],
      recommendation: "",
      tags: [],
      score_breakdown: [],
    },
    {
      area_id: "leadership",
      area_name: "리더십",
      score: 60,
      benchmark: 70,
      gap: 10,
      priority: 3,
      difficulty: "high",
      status_text: "주의",
      issues: [],
      recommendation: "",
      tags: [],
      score_breakdown: [],
    },
  ],
  visibility: {
    score: 76,
    tier: "ok",
    tier_message: "",
    blind_spots: [],
    blind_spot_labels: [],
    blind_spot_tips: [],
  },
  matrix: {
    a_x_as_is: 0,
    a_y_as_is: 0,
    a_x_to_be: 0.7,
    a_y_to_be: 0.7,
    b_x_as_is: 0,
    b_y_as_is: 0,
    b_x_to_be: 0.4,
    b_y_to_be: 0.5,
    a_quadrant_as_is: "균형형",
    a_quadrant_to_be: "성과 책임형",
    b_quadrant_as_is: "자율형",
    b_quadrant_to_be: "책임 운영형",
    pain_point_dispersion: 0.3,
  },
  alignment: { score: 68, base_score: 80, total_penalty: 12, conflicts: [] },
  alignment_map: {
    alignment_score: 64,
    alignment_level: "주의",
    dispersion: 0.2,
    centroid_x: 0,
    centroid_y: 0,
    headline: "",
    summary: "",
    vectors: [],
    axes: [
      {
        domain_id: "compensation",
        domain_name: "보상",
        left_label: "형평",
        right_label: "성과",
        philosophy_label: "성과 차등",
        philosophy_note: null,
        actual_label: "관계 조정",
        policy_direction: "성과 책임",
        alignment_percent: 42,
        status_label: "심각",
        philosophy_position: 0.8,
        actual_position: -0.4,
        tension: 1.2,
        tension_level: "misaligned",
        headline: "",
        evidence: [],
        business_risk: "보상 형평성 논쟁",
      },
    ],
    conflicts: [
      {
        id: "comp-eval",
        title: "보상과 평가 충돌",
        detail: "",
        domains: ["compensation", "evaluation"],
        severity: "high",
      },
    ],
  },
  insights: [],
  foundation_signals: [],
  alignment_signals: [],
};

const report = buildDiagnosticReportViewModel({
  companyName: "테스트컴퍼니",
  completedAt: new Date("2026-06-22T00:00:00.000Z"),
  diagnosis: baseDiagnosis,
  responses: { "L1-2": "51~100명", "L1-3": "빠른 성장", "L1-4": "채용 확대" },
});

const assertions: [string, boolean][] = [
  ["six pages", report.pages.length === 6],
  ["cover title", report.cover.title === "테스트컴퍼니 인사제도 진단 보고서"],
  ["core pattern", report.executive.corePattern.includes("기준 회피")],
  ["honorific blind spot", report.blindSpots[0]?.headline.includes("대표님") ?? false],
  ["priority chain", report.priorityTension.chain.length >= 4],
  ["decision memo", report.decisionMemo.decisions[0]?.includes("성과 차이") ?? false],
];

export const diagnosticReportViewModelSmoke = assertions.every(([, passed]) => passed);
